package drawingUI.entryPage;

import SQLDatabase.connectDB;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import drawingUI.entryPage.Entry;

public class entryPanel extends JPanel implements ActionListener{                        //shows date, select time, button to pick method, back and enter
    //create all components
    JLabel date = new JLabel();
    Entry time = new Entry();
    JButton back = new JButton("Back");
    JButton enter = new JButton("Enter");
    JButton localTime = new JButton("Current Time");
    JRadioButton simple = new JRadioButton("Simple Method");
    JRadioButton comp = new JRadioButton("Comprehensive Method");
    JRadioButton inten = new JRadioButton("Intensive Method");

    simplePanel p1 = new simplePanel();
    compPanel p2 = new compPanel();

    JPanel panel1 = new JPanel();
    JPanel panel2 = new JPanel();
    JPanel panel3 = new JPanel();
    JPanel panel4 = new JPanel();

    public entryPanel(){
        //set labels of entries
        time.newEntry("Time: ");

        //button actions for back and enter
        back.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                System.out.println("Back to view");     //change once other pages are ready
            }
        });
        enter.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
//                System.out.println("Enter log");        //change once other pages are ready
//                String input_date = date.getInfo();     //save input data
//                String input_time = time.getInfo();
//
//                SimpleDateFormat sdf1 = new SimpleDateFormat("MM-dd-yyyy");//convert string input date to sql.date format
//                java.util.Date date = null;
//                try {
//                    date = sdf1.parse(input_date);
//                } catch (ParseException ex) {
//                    ex.printStackTrace();
//                }
//                java.sql.Date sqlDate = new java.sql.Date(date.getTime());
//
//                SimpleDateFormat df = new SimpleDateFormat("HH:mm");//convert string input time to sql.time format
//                java.util.Date time= null;
//                try {
//                    time=df.parse(input_time);
//                } catch (ParseException ex) {
//                    ex.printStackTrace();
//                }
//                java.sql.Time sqltime = new java.sql.Time(time.getTime());
//
//                int ibsl = Integer.parseInt(input_bsl);//convert string bsl to integer
//
//
//                Connection conn = connectDB.connect();//set the connect
//                String Simple_table="CREATE TABLE IF NOT EXISTS patient(id SERIAL primary key,Date date NOT NULL, Time time NOT NULL,bsl integer)";
//                CreateTable.create(Simple_table,conn);
//
//                long id = 0;
//                try {
//                    PreparedStatement stmt = conn.prepareStatement("INSERT INTO patient(date,time,bsl)" + "VALUES(?,?,?)", Statement.RETURN_GENERATED_KEYS);
//                    stmt.setDate(1, sqlDate);
//                    stmt.setTime(2, sqltime);
//                    stmt.setInt(3, ibsl); //insert date into the table
//                    int affectedRows = stmt.executeUpdate();
//                    System.out.println(affectedRows);
//                    // check the affected rows
//                    if (affectedRows > 0) {
//                        // get the ID back
//                        try (ResultSet rs = stmt.getGeneratedKeys()) {
//                            if (rs.next()) {
//                                id = rs.getLong(1);//get the autogenerated id for postgresql
//                            }
//                        } catch (SQLException ex) {
//                            System.out.println(ex.getMessage());
//                        }
//                    }
//                } catch (SQLException ex) {
//                    System.out.println(ex.getMessage());
//
//                }
            }
        });



        //button actions to get local time
        localTime.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                String t = LocalTime.now().format(DateTimeFormatter.ofPattern("HH:mm"));
                time.setInfo(t);            //collect data to db
            }
        });



        //add components with layout
        panel1.add(back);
        panel2.add(date);
        panel2.add(time);
        panel3.add(localTime);
        panel4.add(enter);

        GridLayout layout = new GridLayout(4,1);
        setLayout(layout);
        add(panel1);
        add(panel2);
        add(panel3);
        add(panel4);
    }
    //radio buttons to select method
    @Override
    public void actionPerformed(ActionEvent actionEvent) {
        if(simple.isSelected()){
            JOptionPane.showMessageDialog(this,"You are Male.");
        }
        if(comp.isSelected()){
            JOptionPane.showMessageDialog(this,"You are Female.");
        }
        if(inten.isSelected()){
            JOptionPane.showMessageDialog(this,"Intensive");
        }
    }

}
